### PR TITLE
Fixes #19 PunBB Usergroups Error

### LINKED ISSUE #19: PunBB Usergroups Error
Reference: http://community.mybb.com/thread-107109.html

When no custom usergroups are created the module keeps going while claiming 1 usergroup to import.

http://dev.mybb.com/issues/1767

### PR DESCRIPTION
**Pull request by JN-Jones**
#19

This fixes the usergroups module, seems like the categories module has an error again... :D

### CODE REVIEW

**Comment by Sama34** [comment]
Makes sense.

**Comment by JN-Jones** [comment]
@Sama34 So was this a "this can be merged"? :P

**Comment by Sama34** [comment]
Sure, I see nothing wrong with the edits and your explanation makes sense.

Do you want us to test it? Because that would be tedious for such a little change (:

**Comment by JN-Jones** [comment]
Test it or look at it, at least someone else confirmed I haven't destroyed the merge system :P

**Pull request merged**
