### PR TITLE
Add Discuz! X2.5 and Discuz! UCenter 1.6.0 converters

### LINKED ISSUE #226: UTF-8 issues regarding UTF-8 conversion and others
Preface. I've got a Chinese user based Discuz! forum and have had written a converter for it. During working with the `users` module, I found problems of the Merge System with converting usernames correctly. By looking into the `encode_to_utf8()` function in [`./merge/resources/functions.php`](https://github.com/mybb/merge-system/blob/85a5c9d3005dbfaf7779dce676537c464cc15d04/resources/functions.php#L367) and `check_for_duplicates()` in [`./merge/resources/modules/users`,](https://github.com/mybb/merge-system/blob/85a5c9d3005dbfaf7779dce676537c464cc15d04/resources/modules/users.php#L210) I found something may be causing the problem.

BTW, I've written a [small script](https://gist.github.com/yuliu/9d3f9edc88395026c6d7d50580a1c832) to visually show the problem. It simulates the using of some functions in the Merge System and MyBB, and assumes you want conversion to UTF-8, and `mb_*` & `iconv` functions exist. You should save the file in **ANSI** encoding in a text editor, but not UTF-8, to have it work. Oh, I'm running PHP 5.5 right now.

Let's go on:

- The UTF-8 conversion is working in our demo since `iconv` is given a correct encoding of the original string.

- The culprit of UTF-8 encoding is no correct encoding is given when using a `mb_*` function when converting a string has an encoding other than UTF-8. Because when no encoding is given to a `mb_*` function, it will use `mb_internal_encoding()` which is set to UTF-8 by the Merge System, hard coded in `./merge/index.php`. `encode_to_utf8()` uses `my_strlen()` in MyBB.

- The problem of duplicated user checking is using `my_strtolower()` in MyBB, in which no encoding is given to a `mb_` function.

- A quick fix is to provide `mb_*` functions with an encoding when calling them. But encoding naming convention used by mb diffs from iconv. So we have to do a bit more work.

However, I still can't understand the using of different string lower functions on a username, [via](https://github.com/mybb/merge-system/blob/85a5c9d3005dbfaf7779dce676537c464cc15d04/resources/modules/users.php#L233):
`my_strtolower($duplicate_user['username']) == strtolower($encoded_username)`

Maybe, this [issue](https://github.com/mybb/merge-system/issues/193) is caused by it, too. I've written my versions of these affected functions in my own converter's and module's class, without modifying the basic Merge System. I may make a pull if we come to a conclusion it's wrong usage of `mb_*`.

### LINKED ISSUE #229: Allow boards to run their modules if directly derived from Converter_Module class
If the Merge System can allow this, we can easily write any module even there's no base module class supported naively, by deriving directly from `Converter_Module` abstract class.

I've done so in my Discuz X2.5 converter. A PR is on its way.

By doing so, old or existing modules that are based on the internal module classes are not affected. Nothing should be worried about except that there's no statistic data for those executed customized modules.

Demo result:
```
Modules
-------
The following modules from this converter were completed:
Database Configuration
Settings
Users
Extended User Profile Fields
Extended User Profile Information
Announcements
Thread Prefixes
Forums
Forum Permissions
Moderators
Threads
Polls
Poll Votes
Posts
Attachments


Import Statistics
-----------------
The MyBB import system imported the following from your copy of Discuz! X2.5:
Users:             6,176
Forums:            46
Forum Permissions: 46
Moderators:        46
Threads:           13,252
Posts:             204,805
Attachments:       6,747
Polls:             297
Poll Votes:        816
Settings:          22
```

### PR DESCRIPTION
**Pull request by yuliu**
Add support for converting Discuz! X2.5, `dzx25`.
Add support for converting Discuz! UCenter 1.6.0, `dzucenter`. UCenter 1.6.0 is used across Discuz! version from X2.5 to X3.x.

Although X2.5 is an older version (latest release is in 2017), support for converting X3.x are planned. Placeholders in the `loginconvert.php` plugin are just fine.

Resolve #229, without which some modules must be disabled in the `dzx25` converter. It's compatible with existing modules.
Also try to fix #226, the UTF-8 problem. See the `encode_to_utf8()` function in the board's class.

By the day, I implemented a lot of switches to turn some features on/off, read the README.me files in these two converters for details. The last but not the least, the `dzx25` converter has a built-in generator for URLs redirecting, which is disabled by default. Use it at your own risk.

### CODE REVIEW

**Comment by yuliu** [comment]
Sorry for my inexperienced using of git. I've some questions here:

1. Should I just copy my code into a new branch without checkout to avoid so many in-development commits, which looks rather odd, but just one or a very few commits?
1. The redirects generator is not a original feature that comes with the Merge System. It works as trying to generate some PHP files allowing redirects, let's say a URL like `http(s)://PATH_TO_DISCUZ/forum.php?mod=forumdisplay&fid=333` to `http(s)://PATH_TO_MYBB/forumdisplay.php?fid=333` with a HTTP 301 header. Should I remove it when I pull a request to mybb's merge-system repo?
1. I've made a lot of switches for a user to control the converting, some of which are trying to solve Discuz! problems, is this acceptable?

If anything breaks MyBB's rules, please close this PR, and I'll try to push a more standard one. 😳

**Comment by ShikiSuen** [comment]
I wonder why Discuz converters are not included in the official release.

**Comment by yuliu** [comment]
@ShikiSuen probably Discuz! that is favored by east-Asian forum ownsers isn't popular across the whole wold.

**Comment by ShikiSuen** [comment]
> @ShikiSuen probably Discuz! that is favored by east-Asian forum ownsers isn't popular across the whole wold.

That's not the reason. Discuz is "dying" _from new-tech-lovers' perspective,_ and **is mainly for people who have extremely little ability to maintain web servers by themselves**. There are lots of users who want to try new forums.

By the way, thank you for the Discuz x2 converter you wrote.

**Pull request closed without merging**
