### PR TITLE
Replaced /e modifier with preg_replace_callback

### PR DESCRIPTION
**Pull request by debuggest3**
Support for the /e modifier has been removed in PHP7.

### CODE REVIEW

**Comment by JoshHarmon** [comment]
It's also been changed in the core, so it would be very logical to make the change in the merge system.

**Comment by Stefan-MyBB** [comment]
Since the Merge System is supposed to support PHP 5.2 closures can't be used.

**Comment by JN-Jones** [comment]
@dgrp Can you fix the closures?

**Comment by debuggest3** [comment]
Why do you need to support PHP 5.2? It's been end of life for 5 years already (http://php.net/eol.php).

**Comment by Stefan-MyBB** [comment]
@dgrp Because we claim MyBB 1.8 is compatible with it: http://docs.mybb.com/1.8/install/requirements/
It's certainly not a good idea to break compatibility for such a minor thing.

**Comment by debuggest3** [comment]
I get that, but it doesn't answer my question. At some point the choice was made to support that version of PHP. Only thing I can think of is that a large part of MyBB's userbase is still running PHP 5.2... But I really hope that's not the case.

It's no problem for me changing the pull request, but I just find it sad to see that such a great piece of software is getting potentially held back by not embracing new technologies but instead chooses to stay stuck in the past and keeps supporting old software.

**Comment by Stefan-MyBB** [comment]
While MyBB 2.0 will require PHP 5.5 MyBB 1.8 is supposed to provide compatibility most PHP versions still in use. Unfortunately some hosts never update PHP...

**Comment by JN-Jones** [comment]
Yeah, there are still a lot of hosts on 5.2. I've got quite a lot of requests after I've bumped the requirement for my plugins to 5.3. So it was decided that 1.8 still supports 5.2 however the requirement will be bumped for 2.0.

**Pull request merged**
